// Single source of truth for the policy text — the full page and the consent
// modal render the same sections so they can never drift out of sync.
// Keep this in sync with what APP/main.py's PRIVACY_POLICY_VERSION actually
// governs: a change here that affects how data is handled should be paired
// with bumping that backend constant, which re-prompts every signed-in user.

export interface PolicySection {
  heading: string
  body: string[]
}

export const PRIVACY_POLICY_EFFECTIVE_DATE = 'September 13, 2026'

export const PRIVACY_POLICY_SECTIONS: PolicySection[] = [
  {
    heading: 'Overview',
    body: [
      'Grounded RAG lets you upload documents and ask questions about them, with every answer grounded in and cited back to your own document. This policy explains what data we collect to make that work, who else touches it, and how you can remove it.',
    ],
  },
  {
    heading: 'What we collect',
    body: [
      'Account data: your email address, and a securely hashed password if you sign up with email — we never store your password itself. If you sign in with GitHub or Google, we store the verified email address that provider gives us.',
      'Document content: the files you upload, split into chunks and embedded as vectors for retrieval, plus extracted text and metadata such as filename and page numbers.',
      'Conversation history: the questions you ask and the answers returned, scoped to the document you asked about, so you can resume a conversation later.',
    ],
  },
  {
    heading: 'How we use it',
    body: [
      'Solely to run the product: authenticating you, retrieving relevant passages from your documents, generating grounded answers, and letting you resume past conversations. We do not sell your data, and we do not use your documents to train any model.',
    ],
  },
  {
    heading: 'Where it goes',
    body: [
      'Vectors and document text are stored in Qdrant Cloud, filtered so only your account can retrieve them. Answers are generated by an Azure-hosted OpenAI deployment by default; if you supply your own OpenAI key instead, that request is sent directly with your key and is never stored on our servers. Verification codes are emailed via Azure Communication Services. None of these processors receive more than what is strictly needed to perform their part of the request.',
    ],
  },
  {
    heading: 'Data retention & deletion',
    body: [
      'Your documents, their vectors, and their chat history remain until you delete them. Deleting a document from the workbench removes its database record, its retrieval index, and its vectors from storage — not just a hidden flag. Deleting your account removes everything tied to it; contact us to request that.',
    ],
  },
  {
    heading: 'Your rights',
    body: [
      'You can view and delete any document you have uploaded at any time from the workbench. You can request a copy of your account data, or full account deletion, by contacting us.',
    ],
  },
  {
    heading: 'Security',
    body: [
      'Every document route is scoped to your authenticated account with a signed token. Passwords are hashed, never stored in plain text. Retrieved document text is treated as untrusted data, never as instructions, when generating answers.',
    ],
  },
  {
    heading: "Children's privacy",
    body: [
      'This service is not directed at children under 13, and we do not knowingly collect data from them.',
    ],
  },
  {
    heading: 'Changes to this policy',
    body: [
      'If this policy changes in a way that affects how your data is handled, you will be asked to review and re-accept it the next time you sign in.',
    ],
  },
  {
    heading: 'Contact',
    body: ['Questions about this policy or your data can be sent via the project repository.'],
  },
]
